sblunt/orbitize

orbitize/kepler.py, tests/test_kepler_solver.py
I added the kepler.py module and a test for it. I'm using Rob De Rosa's eccentricity solver, which seems to produce different answers than James' of around ~10 microarcseconds. Not sure why, but something to look into in the future.
=> Added Keplerian orbital solver

orbitize/priors.py, orbitize/sampler.py, orbitize/system.py, tests/test_mcmc.py
At long last, it doesn't crash.
=> PTMCMC Initial Working Implementation

orbitize/read_input.py, tests/test_read_input.py, tests/test_val.csv
To match a measurement with a particular object. Tests and sample files updated too.
=> Added ``object`` column to data table 

contributors.txt, orbitize/kepler.py, orbitize/lnlike.py, orbitize/read_input.py, orbitize/sampler.py, orbitize/system.py, setup.py, tests/test_api.py, tests/test_kepler_solver.py, tests/test_mcmc.py
- "number of models" is now the last dimension in every variable in a System class. I removed a small bit of code in kepler.py to make this happen, and modified some code in system.py.
- other small comment & documentation changes
@semaphoreP give this a look when you have a chance to make sure I fixed everything the way you intended. I didn't change anything in sampler.py.
=> Address Issue #25

orbitize/__init__.py, orbitize/results.py, orbitize/system.py, tests/test_api.py
- added list of labels to System class (issue #34) and added `results` attribute to System class
- added unit test for System labels
- fleshed out docstring of Results class
=> Improve system+results

orbitize/sampler.py, requirements.txt, setup.py
Minor changes to fully embrace ptemcee for PT sampling
=> Switch ptemcee

.gitignore, .travis.yml, contributors.txt, orbitize/_kepler.pyx, orbitize/kepler.c, orbitize/kepler.py, setup.py, tests/test_kepler_solver.py
Implementation of kepler module in C. I've installed it successfully on my Windows Subsystem for Linux (Ubuntu) and Windows terminals. Includes profiling tool and is compatible with whichever archaic C compiler that Travis uses (pre C99).
=> Kepler module implemented in C

orbitize/kepler.py, orbitize/results.py, orbitize/system.py, tests/test_api.py, tests/test_kepler_solver.py
This should correct the order of orbital elements in all places, as discussed in #45 
In most places, this amounts to switching the positions of `inc` and `epp`
=> Fix orbel order

docs/tutorials/Plotting_tutorial.ipynb, orbitize/results.py
Very minor changes. The only cells in the notebook that has changes are the Markdown cells, so I didn't re-run the notebook and hopefully you won't have to either!
=> Plot tutorial fix

orbitize/results.py, tests/test_results.py
Add flexibility to the colorbar such that the user can select whether the colorbar is parameterized by either the epoch or an orbital element of their choice.
=> colorbar flexibility

contributor_guidelines.md
Added some text to address Issue #92. Let me know if there's anything that should be edited or added!
=> Notes on how to work collaboratively on branches

orbitize/results.py
Hey @isabelangelo I think I figured it out. (see Issue #95)
=> Filter astropy ERFA warnings

orbitize/sampler.py
hopefully it worked this time!
=> added MCMC progress bar

docs/tutorials.rst, docs/tutorials/Modifying_MCMC_initial_positions.ipynb
For Issue #116 
In this tutorial, I walked through how to create a N-d Gaussian cloud/ball of walkers centered on a given point with some given spread. But this can start walkers outside of prior space or even outside of physically possible values. 
So, a user would need to do some validation or change the distribution of some parameters to be non-Gaussian. I gave an example of both in the tutorial but the tutorial itself does not fix every possible problem. I decided to leave it to the user to do the rest but if you think there are more things needed, then let me know!
=> MCMC Walker start position tutorial

docs/formatting_inputs.rst
=> read_input doc update

orbitize/results.py, tests/test_results.py
Partially in response to the referee, partially in response to everyone else who has (rightfully) complained about this. orbitize! output is still given in radians.
=> Default corner plot now plots angles in degrees

orbitize/read_input.py, orbitize/results.py
Pulling @aryadas's PR into a base repo branch so I can make a few small changes
=> Explicitly convert input table into masked table

.travis.yml, docs/installation.rst, orbitize/read_input.py, requirements.txt
Incorporate @aryadas98's fix for issue #152. This PR will make orbitize! non-Python 2 compliant.
=> Issue #152 fix

tests/test_multiplanet.py
I removed eccentricity from the MCMC test for multiplanet. It should be easier for MCMC to converge without it now. Couldn't get the numpy.seed() working so that MCMC is predictable, but I ran it multiple times and now the masses change by < 10%.
=> Fix Multiplanet Test

.gitignore, orbitize/sampler.py, orbitize/system.py, tests/test_OFTI.py
=> Pan priors

docs/installation.rst
=> add instructions for installing ptemcee on windows

contributor_guidelines.md, docs/index.rst
Add community agreement to `contributor_guidelines.md` and index page of docs
=> Community agreement

orbitize/results.py, tests/test_results.py
Fixes for issue #168:
- now you can pass a preexisting Figure object into results.plot_orbit
- colorbar label is now "Epoch [year]"
- corner plot maker can now handle fixed parameters without crashing
=> Plotting improvements

README.md, orbitize/sampler.py, tests/test_OFTI.py
Hey all, I've finally fixed issue #144! Check it out and let me know what you think. Functionality and a few new unit tests.
(Originally did this on a different branch, but built it off of develop instead of main by accident. Then decided it would be simpler to just make a new branch rather than rebasing the old one since it was so little code)
=> account for user-defined priors on PAN

orbitize/hipparcos.py, orbitize/read_input.py, orbitize/system.py, tests/test_secondary_rvs.py
Partially addresses issue #275
=> Add pl rv unit tests

orbitize/plot.py, orbitize/results.py
Address issue #316 and #309 (same issue)
=> Fix multiple plotting issues

orbitize/gaia.py
As in #352 , updated where the hgca was being downloaded from to the vizier FTP source and added the "ignore_missing_end" kwarg to the fits.open
=> update hgca edr3 to stable vizier url

orbitize/basis.py, orbitize/system.py, tests/test_secondary_rvs.py
Fixing as many "easy" bugs as I can in the next 24 hours challenge!
So far, the list includes:
- fixing #347 : minor documentation fix for the xyz basis
=> Fix as many small bugs as i can
