- contributors.txt
- orbitize/kepler.py
- tests/test_kepler_solver.py
This upgrade addresses issue #16 and allows kepler.py's calc_orbit to handle arrays as well as scalars as input for orbital elements so that we solve many orbits simultaneously.
Note that calc_orbit takes in epochs which has size n_dates and orbital elements which has size n_orbs. For most cases, n_dates << n_orbs so almost all of the loops in calc_orbit is a loop through the epochs. The exception is the eccentric anomaly solver, which can only solve for one eccentricity at a time, so it is a loop through each set of orbital elements. Something to keep in mind if we need further speedups.
So far, a speed test with 100,000 simultaneous orbits on this branch takes 3.7 seconds. Running the old version (scalars for orbital elements) 100,000 times takes about 90 seconds.
> Vectorize kepler

- orbitize/kepler.py
- tests/test_kepler_solver.py
A few modifications:
- Element, parallax and mtot vectors are now converted into (n_orbs, n_dates) arrays. A bit clunky. The alternative is to use [:, None] indexing, although that would have to be put everywhere in the code, so maybe this is neater?
- manom now wrapped between 0->2pi. This significantly changes the output for high eccentricity orbits.
- raoff, deoff and vz calculation vectorized
- eanom calculation vectorized
- Split the newton solver into its own function.
- Various modifications for consistency, and removed some unused variables.
> Eanom optimizations

- setup.py
the pytest.approx() function was added in 3.0.0
> pytest requires >=3.0.0

- orbitize/__init__.py
- orbitize/sampler.py
- tests/test_mcmc.py
sampler object's initialization can specify `nthreads` for parallelization. 
Since `emcee` will remove their PT sampler in the next release, I've added the Ensemble Sampler from `emcee` as an alternative (a good replacement might be `ptemcee`)
Addresses Issue #30
> Multi-threading support for MCMC samplers

- orbitize/kepler.py
This is done in case user passes astropy.Table Column objects (which would be a lot slower)
This should wrap up #20 if @rjderosa agrees that it addresses the concern!
> Force iterative part of numpy kepler solver to work with np.array 

- orbitize/sampler.py
- orbitize/system.py
- tests/test_OFTI.py
- tests/test_api.py
- tests/test_mcmc.py
Ok, I think the second try starting fresh was a lot more successful. 
- Re-implemented @sblunt's changes to system.py. 
- The results posteriors are always the same size, no matter if mass/plx are fixed. 
- Similarly, OFTI's samples are also fixed size. I think the slight increase in memory usage is negligible here. 
- MCMC now samples only the non-fixed parameters, but will return posteriors that include the fixed parameters. 
- Under this philosophy, it is up to the samplers to handle the fixed parameters gracefully (system.compute_model() requires mass and parallax as params as a result right now, since the system right now does not care about fixed parameters).
- Also, I fixed a bug where the Ensemble Sampler wasn't using the priors (was only calling the likelihood function). …
> Fix mass and parallax 2

- .travis.yml
- docs/formatting_inputs.rst
- orbitize/driver.py
- orbitize/read_input.py
- orbitize/system.py
- requirements.txt
- tests/test_api.py
- tests/test_driver.py
- tests/test_mcmc.py
- tests/test_read_input.py
- tests/test_system.py
This update deprecates two functions in read_input: read_formatted_file and read_orbitize_input and combines their functionality in a new function: read_input
Also includes minor typo fixes and updates all calls to the deprecated functions to use the new functions instead. This update adds the deprecation module to label and track deprecated functions. Users will be asked to use read_file instead.
Currently, the above deprecated functions will still exist and serve as wrappers to read_input until version 2.0. New unit tests developed to test this functionality. These new unit tests have a decorator that will cause the tests to fail if we forget to actually remove the function in version 2.0.
Docs are also updated.
Finally, this also addresses Issue #80 with updates to Driver.py to allow …
> Driver & read_input fix

- orbitize/priors.py
- orbitize/results.py
- tests/test_priors.py
This was causing unphysical (negative) stellar masses to be returned. Fixed.
> Do not include negative values in the Gaussian prior

- orbitize/basis.py
- orbitize/driver.py
- orbitize/kepler.py
- orbitize/results.py
- orbitize/sampler.py
- orbitize/system.py
- tests/test_conversions.py
- tests/test_driver.py
- tests/test_results.py
This PR addresses issues #61 and #62. The key changes are
- utilities in manipulate tau (change reference epoch, and get date of periastron) using the basis.py module
- system/driver now can set the tau reference epoch as an init argument
- default reference epoch is Jan 1, 2020 (MJD=58849) instead of the old MJD = 0
- Results class now saves tau reference epoch to the header and can handle the reference epoch internally so user can still pass in MJD dates
This PR modifies the Results and OFTI classes, as well lots of other miscellaneous bits of code, so it would be good to verify I didn't mess up anyone's code. Another open question is whether we want to call it basis.py or something else -- my hope in the future is that if we have different sets of orbital elements, we could include …
> Tau utilities and customization

- orbitize/sampler.py
- orbitize/system.py
- tests/test_OFTI.py
- tests/test_system.py
This is a fix for Issue #108 
As discussed, I remove `sampler.data_table` and `sampler.input_table` in favour of `system.data_table` and `system.input_table`. I moved the actual radec/seppa conversion calculation to be done within the `system` object, as I wanted it to change `system.data_table` in place while also updating the arrays `system.radec` and `system.seppa` used to keep track of which entries are in which format. I believe these arrays are necessary in additional to the `quant_type` column of `data_table` because it sorts them by body number. 
Right now, these conversions are done for one body at a time since we don't do multi-planet yet. It seems like the OFTI sampler was already hard-coded for just 1 planet so I kept it that way to keep the scope of this PR only on #108. It …
> Fix radec/seppa conversion with OFTI sampler

- orbitize/read_input.py
- requirements.txt
to let the user know there was a problem finding/reading the file and if the epoch was not given as MJD (or JD).
In response to Issue #111.
> Added two exception messages 

- orbitize/sampler.py
in the mcmc sampler, logp is summed if there is more than one prior with a parameter, and likelihood evaluation skipped if prior = -inf.
> skip likelihood evaluation if prior is -inf

- orbitize/sampler.py
@vighnesh-nagpal I found a minor bug in the parallel processing code. A new random seed needs to be generated for each child process, otherwise they will all generate the same orbits. Tough bug to catch. See here for an example: https://stackoverflow.com/questions/9209078/using-python-multiprocessing-with-different-random-seed-for-each-process
Once you approve I can pull this into master 1-2-3!
> Add random seed to child processes

- orbitize/results.py
- orbitize/system.py
- tests/test_system.py
Go from this:
to this:
I left this as a keyword for the user to choose because for some orbits I think folks will want to show the 0/360 jumps. It just looks bad for short arcs.
> Add a keyword for plotting orbits that cross PA=360

- orbitize/results.py
I just noticed that the orbit plots have RA in the wrong direction. Positive RA should go to the left, not the right. I added one line of code to invert the x-axis. I edited this online, so definitely wait for the tests to pass first to make sure I didn't make any typos.
> Plot RA with positive to the left as is convention

- .gitignore
- orbitize/results.py
- tests/test_results.py
Small bugfix for a minor issue I believe was introduced in the RV PR. `Results.labels` was being loaded into a 2d array rather than a list, which was causing corner plots to fail. Easy fix!
> fix bug that was causing corner to fail on loaded results objs

- orbitize/system.py
- tests/test_multiplanet.py
This fixes an issue where we weren't properly handling what should be the total mass in multi-planet systems (affects the orbital period). I checked against N-body integrators, and we should use the sum of all masses with r <= distance of the planet when computing mtot. You can think of this as an application of Gauss's law where the force on the planet is equal to the force if all the mass within a sphere is at the center of a sphere. 
I think this is right at least...
> improved mtot calculation for multiplanet

- orbitize/results.py
Hello,
Me and my team(@Khadir991 and @Slimane-ABDENNOUR) thought that the lines `535, 536` on `orbitize/main` 
```
yr_epochs = Time(epochs_seppa[i, :], format='mjd').decimalyear
plot_epochs = np.where(yr_epochs <= sep_pa_end_year)[0] # < ----
yr_epochs = yr_epochs[plot_epochs] 			# < ----
```
were redundant.
As `epochs_seppa[i, :]` are generated with `np.linspace` :
```
epochs_seppa[i, :] = np.linspace(
start_mjd,
Time(sep_pa_end_year, format='decimalyear').mjd,
num_epochs_to_plot
)
```
And in the `orbitize/main` `start_mjd` is guaranteed to be smaller than `sep_pa_end_year`, 
the `np.where` conditions should be met for the full array everytime. 
And if the condition is not met (by at least one element of the array) an error would occur (similar to the one in [Codeastro's broken_orbitize …
> Remove redundant code

- .travis.yml
- orbitize/system.py
- tests/test_multiplanet.py
- tests/test_multiplanet_rebound.py
Only inner planets perturb the visual orbits of outer planets. Outer planets are not accounted in inner planet orbits. I checked against REBOUND and this is indeed a better approximation (no test yet, unless we want to formally require REBOUND in our CI). 
Fixes issue #191
> account for inner planets only in perturbations

- docs/faq.rst
- docs/faq/Time_Of_Periastron.ipynb
- docs/index.rst
- orbitize/basis.py
- orbitize/radvel_utils/compute_sep.py
- tests/test_conversions.py
New FAQ section of docs, with a new notebook on tau/tp/M. 
One question, I realized tp is named inconsistently. In `orbitize.basis`, it is referred to as t0. Do we have a preferred notation?
> Add FAQ section with tau docs.

- orbitize/results.py
Address issue #221, and partially #219. Now catches error if version number is not in the results files.
> error catch for old results without versioning

- docs/faq/Time_Of_Periastron.ipynb
This is a very minor typo correction to change "literuatre" to "literature".
Thanks for the great documentation!
> Correct typo on documentation page

- tests/conftest.py
Run `pytest --mode codeastro` and if all tests pass, you get a secret token at the end. Pretty basic obfuscation but prevents any simple grep of the code to find.
> add token for running codeastro tests

- orbitize/results.py
Addresses issue #234 (see plots below). Also I noticed that line 319 should be ` if np.std(self.post[:, index_num]) > 0:` because `i` indexes into the `param_list` array, not `self.post`. 
Reproducing the issue #234, now behavior is good:
```
corner_figure_median_95 = result_copy.plot_corner(
param_list = ['sma1', 'ecc1', 'inc1', 'aop1', 'pan1', 'tau1'],
show_titles = True
)
```
```
corner_figure_median_95 = result_copy.plot_corner(
param_list = ['tau1','sma1','pan1','aop1','ecc1','inc1'],
show_titles = True
)
```
> fix #234. Also another possible bug.

- orbitize/results.py
- orbitize/sampler.py
- tests/test_mcmc.py
- tests/test_results.py
Add `param_idx` attributes to the `Results` and `MCMC` classes for debugging aid.
> Param idx labels for Results and MCMC classes

- orbitize/results.py
- tests/test_results.py
The text fields in results.data should now be str and not bytes. Addresses #256, and possibly also @252.
> use astropy tables in results to address #256

- orbitize/system.py
We should set track_planet_perturbs to True if the user wants to fit for a dynamical mass AND
1. there is data other than relative astrometry and ** stellar ** RVs (i.e. absolute astrometry of the primary)
2. there is more than one secondary body
> address #248

- orbitize/plot.py
- orbitize/read_input.py
- orbitize/results.py
- orbitize/sampler.py
This is a minor PR that fixes the issue related to several deprecated `numpy` functions (in version 1.24) for certain data types (see issues #330 and #329).
I have updated the use of `np.float`, `np.int`, and `np.str`. This fix should also work with `numpy` versions older than 1.24.
Not related, but I also added a warning in `plot_orbits` related to the `rv_time_series` parameter, just for convenience.
Let me know in case you have any feedback 😊
> Updated deprecated numpy functions

- requirements.txt
- tests/test_priors.py
- tests/test_rebound.py
The truth values have an extra 1/sqrt(2pi) that we aren't accounting for. I multiplied it to the truth values and the test should pass now.
> fix orbitize tests

- .github/workflows/run-notebooks.yml
- orbitize/nbody.py
it looks like the latest version of REBOUND no longer has the `calculate_com()` function and this causes our tests to fail. Replacing with the `com()` function.
> Replace depricated calculate_com function

- .github/workflows/joss-compile.yml
- .github/workflows/python-package.yml
- docs/index.rst
- orbitize/__init__.py
- orbitize/system.py
- pyproject.toml
- requirements.txt
- setup.py
- tests/test_nested_sampler.py
Not everything is working yet but I want to test the automatic notebook running workflow which triggers on pr to main
> modernize orbitize install & fix ci tests
